COMMON_DATA_TYPES_MAP = {
        '01': 'Flags',
        '02': 'Incomplete List of 16-bit Service or Service Class UUIDs',
        '03': 'Complete List of 16-bit Service or Service Class UUIDs',
        '04': 'Incomplete List of 32-bit Service or Service Class UUIDs',
        '05': 'Complete List of 32-bit Service or Service Class UUIDs',
        '06': 'Incomplete List of 128-bit Service or Service Class UUIDs',
        '07': 'Complete List of 128-bit Service or Service Class UUIDs',
        '08': 'Shortened Local Name',
        '09': 'Complete Local Name',
        '0A': 'Tx Power Level',
        '0D': 'Class of Device',
        '0E': 'Simple Pairing Hash C-192',
        '0F': 'Simple Pairing Randomizer R-192',
        '10': 'Security Manager TK Value',
        '11': 'Security Manager Out of Band Flags',
        '12': 'Peripheral Connection Interval Range',
        '14': 'List of 16-bit Service Solicitation UUIDs',
        '15': 'List of 128-bit Service Solicitation UUIDs',
        '16': 'Service Data - 16-bit UUID',
        '17': 'Public Target Address',
        '18': 'Random Target Address',
        '19': 'Appearance',
        '1A': 'Advertising Interval',
        '1B': 'LE Bluetooth Device Address',
        '1C': 'LE Role',
        '1D': 'Simple Pairing Hash C-256',
        '1E': 'Simple Pairing Randomizer R-256',
        '1F': 'List of 32-bit Service Solicitation UUIDs',
        '20': 'Service Data - 32-bit UUID',
        '21': 'Service Data - 128-bit UUID',
        '22': 'LE Secure Connections Confirmation Value',
        '23': 'LE Secure Connections Random Value',
        '24': 'URI',
        '25': 'Indoor Positioning Indoor Positioning Service',
        '26': 'Transport Discovery Data Transport Discovery Service',
        '27': 'LE Supported Features',
        '28': 'Channel Map Update Indication',
        '29': 'PB-ADV {Mesh}',
        '2A': 'Mesh Message',
        '2B': 'Mesh Beacon',
        '2C': 'BIGInfo',
        '2D': 'Broadcast_Code',
        '2E': 'Resolvable Set Identifier',
        '2F': 'Advertising Interval - long',
        '30': 'Broadcast_Name',
        '31': 'Encrypted Advertising Data',
        '32': 'Periodic Advertising Response Timing Information',
        '34': 'Electronic Shelf Label',
        '3D': '3D Information Data',
        'FF': 'Manufacturer Specific Data'
    }
